### ISSUE TITLE
Move to workshopper org?

### ISSUE THREAD

**Issue by llkats** [workshopper/scope-chains-closures#28]
As part of an effort to update and maintain the NodeSchool curriculum, we have been asking Core Curriculum workshopper owners if they would consider moving their projects under the `workshopper` organization. 

Would you be willing to migrate scope-chains-closures over? Discussion is linked here: https://github.com/workshopper/org/issues/10 and please let me know if you have any questions!

**Comment by SomeoneWeird** [comment]
+1

**Comment by tapsboy** [comment]
@jesstelford Your call

**Comment by jesstelford** [comment]
I am 100% on board with the transfer - thanks for the invitation :)

@llkats I just tried the transfer, and it looks like I don't have permissions in the `workshopper` org - can I be added (even if only temporarily) to make the transfer?

_Edit_: Sorry for taking so long to reply :/

**Comment by martinheidegger** [comment]
@jesstelford I invited you ^_^

**Comment by jesstelford** [comment]
Done :tada:

**Comment by jesstelford** [comment]
@SomeoneWeird Looks like I lost admin rights in the transfer - can you add me back in / the group `scope-chains-closures-leads` as a collaborator?

**Comment by martinheidegger** [comment]
@jesstelford you should have admin rights (on the repo)
