### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by andruhon** [workshopper/scope-chains-closures#3]
Trying to run this lesson on the Windows 8,
`>scope-chains-closures` causes:
The system cannot find the path specified.

**Comment by jesstelford** [comment]
Hmm, intersting. I've not tested it on Windows before.

In what shell environment are you running it (git-bash, mingw, etc)?

**Comment by andruhon** [comment]
Just from windows command line. You want to say, that this lesson is platform dependent?

**Comment by andruhon** [comment]
Hmm, tried to run it from module directory as `node runner.js` - and it seems to work fine.

**Comment by andruhon** [comment]
I see. It creates scope-chains-closures.cmd with the following content
`@IF EXIST "%~dp0\/bin/sh.exe" (
  "%~dp0\/bin/sh.exe"  "%~dp0\node_modules\scope-chains-closures\runner.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  /bin/sh  "%~dp0\node_modules\scope-chains-closures\runner.js" %*
)`
sh.exe cannot, obviously be found

I think it is caused by: #!/bin/sh in runner.js

**Comment by andruhon** [comment]
It, indeed, fixes the problem on windows:
https://github.com/andruhon/scope-chains-closures/commit/3a3f437c4eadce54d9686f829fc8353370c4cce5

So the hack described on http://sambal.org/?p=1014 gives with one hand, but takes crossplatformity with another. You, probably, need some workaround to make it work on windows with this hack.

Do you actually need this hack for this lesson? I think that this lesson supposed to be installed by newbies globally and npm will create sh file on installation. I think it is quite unlikely that someone will run it directly from shell.

**Comment by mesteves** [comment]
Hi,

I've also had the same problem: 

https://github.com/nodeschool/discussions/issues/1189

**Comment by jesstelford** [comment]
Thanks for investigating the issue everyone, I really appreciate the help. #4 fixed the issue, and it's now published in **v1.0.3**. Run `npm install -g scope-chains-closures` to update.
