### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by pwndude** [workshopper/scope-chains-closures#36]
When the first workshop is selected, the following warning shows at the end of output:

(node:19020) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Comment by jazzlee** [comment]
(node:9568) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Comment by OlegK96** [comment]
Any solution to this?

**Comment by 499070844** [comment]
(node:1248) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Comment by daxsis** [comment]
`npm\node_modules\scope-chains-closures\node_modules\adventure\index.js`
line 288:8
`Shop.prototype.save = function (key) {
    fs.writeFile(this.files[key], JSON.stringify(this.state[key]), function(err){
        if(err) throw err;
    });
};`

**Comment by finnp** [comment]
Fixed with `@workshoppers/scope-chains-closures`
